name: translate_gen
description: Package provides tools to assist with translation tasks in Flutter projects, including preparing configuration files, extracting translatable strings, and replacing them based on a configuration.
version: 1.0.2
# repository: https://github.com/my_org/my_repo
homepage: https://github.com/OmarMahmoud-alam/translate_gen
repository: https://github.com/OmarMahmoud-alam/translate_gen
issue_tracker: https://github.com/OmarMahmoud-alam/translate_gen/issues

environment:
  sdk: '>=2.18.0 <4.0.0'
# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  yaml: ^3.1.0
  args: ^2.4.2
  path: ^1.9.0
  analyzer: ^6.4.1
  crypto: ^3.0.3
  dart_style: ^2.0.0
  http: ^1.4.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
